name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Update apt-get
      run: sudo apt-get update
    - name: make without anything
      run: make
    - name: test without anything
      run: make test
    - name: Install CFITSIO
      run: sudo apt-get install libcfitsio-dev
    - name: make with CFITSIO
      run: make
    - name: Install GSL
      run: sudo apt-get install libgsl-dev
    - name: make with GSL
      run: make
    - name: test with GSL
      run: make test
    - name: Run simulator test
      run: ./test_patpc.sh
